//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Training4
{
    using System;
    using System.Collections.Generic;
    
    public partial class KhachHang
    {
        public int ID { get; set; }
        public string TenKhachHang { get; set; }
        public System.DateTime NgaySinh { get; set; }
        public Nullable<int> idDiaChi { get; set; }
        public string SDT { get; set; }
        public Nullable<double> SoTien { get; set; }
        public Nullable<bool> Active { get; set; }
    
        public virtual DiaChi DiaChi { get; set; }
    }
}
